[package]
name = "day10"
version = "0.1.0"
authors = ["Beno√Æt Allard <benoit.allard@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
